### ISSUE TITLE
Aero Set C for Porsche 9.3 (964) and Aero Set H for R32 not showing up in WMMT6

### ISSUE THREAD

**Issue by Bluuwolfly** [damon-murdoch/wmmt-car-editor#1]
Exactly as the title says,both of these aero sets aren't showing up ingame for me and instead show the stock bodykit

**Comment by damon-murdoch** [comment]
- Aero Set H is only available in 6R onward unfortunately :(
Source: https://wikiwiki.jp/wmmt/SKYLINE%20GT-R%20%28BNR32%29?word=r32

- Aero set C for Porsche is available, but has weird behavior because it has less aero kits than compared to other cars. You should be able to pick aero set C for the 964 by selecting Aero Kit K in the menu :)

Sorry for the confusion, but it is hard to prepare for edge cases like this when I have to make the editor work for every possible model. I hope you understand :)
